#pragma once

#include "ScanCodes.hpp"

typedef uint32_t KeyCode;

#define ELLIPSE_KEY_SCANCODE_MASK (1u<<30)
#define ELLIPSE_SCANCODE_TO_KEYCODE(X)  (X | ELLIPSE_KEY_SCANCODE_MASK)
#define ELLIPSE_KEY_UNKNOWN    0
#define ELLIPSE_KEY_RETURN '\r'
#define ELLIPSE_KEY_ESCAPE '\x1B'
#define ELLIPSE_KEY_BACKSPACE  '\b'
#define ELLIPSE_KEY_TAB    '\t'
#define ELLIPSE_KEY_SPACE  ' '
#define ELLIPSE_KEY_EXCLAIM    '!'
#define ELLIPSE_KEY_DBLAPOSTROPHE   '"'
#define ELLIPSE_KEY_HASH   '#'
#define ELLIPSE_KEY_PERCENT    '%'
#define ELLIPSE_KEY_DOLLAR '$'
#define ELLIPSE_KEY_AMPERSAND  '&'
#define ELLIPSE_KEY_APOSTROPHE  '\''
#define ELLIPSE_KEY_LEFTPAREN  '('
#define ELLIPSE_KEY_RIGHTPAREN ')'
#define ELLIPSE_KEY_ASTERISK   '*'
#define ELLIPSE_KEY_PLUS   '+'
#define ELLIPSE_KEY_COMMA  ','
#define ELLIPSE_KEY_MINUS  '-'
#define ELLIPSE_KEY_PERIOD '.'
#define ELLIPSE_KEY_SLASH  '/'
#define ELLIPSE_KEY_0  '0'
#define ELLIPSE_KEY_1  '1'
#define ELLIPSE_KEY_2  '2'
#define ELLIPSE_KEY_3  '3'
#define ELLIPSE_KEY_4  '4'
#define ELLIPSE_KEY_5  '5'
#define ELLIPSE_KEY_6  '6'
#define ELLIPSE_KEY_7  '7'
#define ELLIPSE_KEY_8  '8'
#define ELLIPSE_KEY_9  '9'
#define ELLIPSE_KEY_COLON  ':'
#define ELLIPSE_KEY_SEMICOLON  ';'
#define ELLIPSE_KEY_LESS   '<'
#define ELLIPSE_KEY_EQUALS '='
#define ELLIPSE_KEY_GREATER    '>'
#define ELLIPSE_KEY_QUESTION   '?'
#define ELLIPSE_KEY_AT '@'
#define ELLIPSE_KEY_LEFTBRACKET    '['
#define ELLIPSE_KEY_BACKSLASH  '\\'
#define ELLIPSE_KEY_RIGHTBRACKET   ']'
#define ELLIPSE_KEY_CARET  '^'
#define ELLIPSE_KEY_UNDERSCORE '_'
#define ELLIPSE_KEY_GRAVE  '`'
#define ELLIPSE_KEY_a  'a'
#define ELLIPSE_KEY_b  'b'
#define ELLIPSE_KEY_c  'c'
#define ELLIPSE_KEY_d  'd'
#define ELLIPSE_KEY_e  'e'
#define ELLIPSE_KEY_f  'f'
#define ELLIPSE_KEY_g  'g'
#define ELLIPSE_KEY_h  'h'
#define ELLIPSE_KEY_i  'i'
#define ELLIPSE_KEY_j  'j'
#define ELLIPSE_KEY_k  'k'
#define ELLIPSE_KEY_l  'l'
#define ELLIPSE_KEY_m  'm'
#define ELLIPSE_KEY_n  'n'
#define ELLIPSE_KEY_o  'o'
#define ELLIPSE_KEY_p  'p'
#define ELLIPSE_KEY_q  'q'
#define ELLIPSE_KEY_r  'r'
#define ELLIPSE_KEY_s  's'
#define ELLIPSE_KEY_t  't'
#define ELLIPSE_KEY_u  'u'
#define ELLIPSE_KEY_v  'v'
#define ELLIPSE_KEY_w  'w'
#define ELLIPSE_KEY_x  'x'
#define ELLIPSE_KEY_y  'y'
#define ELLIPSE_KEY_z  'z'
#define ELLIPSE_KEY_CAPSLOCK   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CAPSLOCK)
#define ELLIPSE_KEY_F1 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F1)
#define ELLIPSE_KEY_F2 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F2)
#define ELLIPSE_KEY_F3 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F3)
#define ELLIPSE_KEY_F4 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F4)
#define ELLIPSE_KEY_F5 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F5)
#define ELLIPSE_KEY_F6 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F6)
#define ELLIPSE_KEY_F7 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F7)
#define ELLIPSE_KEY_F8 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F8)
#define ELLIPSE_KEY_F9 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F9)
#define ELLIPSE_KEY_F10    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F10)
#define ELLIPSE_KEY_F11    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F11)
#define ELLIPSE_KEY_F12    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F12)
#define ELLIPSE_KEY_PRINTSCREEN    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PRINTSCREEN)
#define ELLIPSE_KEY_SCROLLLOCK ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SCROLLLOCK)
#define ELLIPSE_KEY_PAUSE  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PAUSE)
#define ELLIPSE_KEY_INSERT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_INSERT)
#define ELLIPSE_KEY_HOME   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_HOME)
#define ELLIPSE_KEY_PAGEUP ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PAGEUP)
#define ELLIPSE_KEY_DELETE '\x7F'
#define ELLIPSE_KEY_END    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_END)
#define ELLIPSE_KEY_PAGEDOWN   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PAGEDOWN)
#define ELLIPSE_KEY_RIGHT  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RIGHT)
#define ELLIPSE_KEY_LEFT   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_LEFT)
#define ELLIPSE_KEY_DOWN   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_DOWN)
#define ELLIPSE_KEY_UP ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_UP)
#define ELLIPSE_KEY_NUMLOCKCLEAR   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_NUMLOCKCLEAR)
#define ELLIPSE_KEY_KP_DIVIDE  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_DIVIDE)
#define ELLIPSE_KEY_KP_MULTIPLY    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MULTIPLY)
#define ELLIPSE_KEY_KP_MINUS   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MINUS)
#define ELLIPSE_KEY_KP_PLUS    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_PLUS)
#define ELLIPSE_KEY_KP_ENTER   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_ENTER)
#define ELLIPSE_KEY_KP_1   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_1)
#define ELLIPSE_KEY_KP_2   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_2)
#define ELLIPSE_KEY_KP_3   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_3)
#define ELLIPSE_KEY_KP_4   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_4)
#define ELLIPSE_KEY_KP_5   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_5)
#define ELLIPSE_KEY_KP_6   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_6)
#define ELLIPSE_KEY_KP_7   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_7)
#define ELLIPSE_KEY_KP_8   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_8)
#define ELLIPSE_KEY_KP_9   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_9)
#define ELLIPSE_KEY_KP_0   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_0)
#define ELLIPSE_KEY_KP_PERIOD  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_PERIOD)
#define ELLIPSE_KEY_APPLICATION    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_APPLICATION)
#define ELLIPSE_KEY_POWER  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_POWER)
#define ELLIPSE_KEY_KP_EQUALS  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_EQUALS)
#define ELLIPSE_KEY_F13    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F13)
#define ELLIPSE_KEY_F14    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F14)
#define ELLIPSE_KEY_F15    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F15)
#define ELLIPSE_KEY_F16    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F16)
#define ELLIPSE_KEY_F17    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F17)
#define ELLIPSE_KEY_F18    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F18)
#define ELLIPSE_KEY_F19    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F19)
#define ELLIPSE_KEY_F20    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F20)
#define ELLIPSE_KEY_F21    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F21)
#define ELLIPSE_KEY_F22    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F22)
#define ELLIPSE_KEY_F23    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F23)
#define ELLIPSE_KEY_F24    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_F24)
#define ELLIPSE_KEY_EXECUTE    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_EXECUTE)
#define ELLIPSE_KEY_HELP   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_HELP)
#define ELLIPSE_KEY_MENU   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_MENU)
#define ELLIPSE_KEY_SELECT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SELECT)
#define ELLIPSE_KEY_STOP   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_STOP)
#define ELLIPSE_KEY_AGAIN  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AGAIN)
#define ELLIPSE_KEY_UNDO   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_UNDO)
#define ELLIPSE_KEY_CUT    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CUT)
#define ELLIPSE_KEY_COPY   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_COPY)
#define ELLIPSE_KEY_PASTE  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PASTE)
#define ELLIPSE_KEY_FIND   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_FIND)
#define ELLIPSE_KEY_MUTE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_MUTE)
#define ELLIPSE_KEY_VOLUMEUP   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_VOLUMEUP)
#define ELLIPSE_KEY_VOLUMEDOWN ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_VOLUMEDOWN)
#define ELLIPSE_KEY_KP_COMMA   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_COMMA)
#define ELLIPSE_KEY_KP_EQUALSAS400 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_EQUALSAS400)
#define ELLIPSE_KEY_ALTERASE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_ALTERASE)
#define ELLIPSE_KEY_SYSREQ ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SYSREQ)
#define ELLIPSE_KEY_CANCEL ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CANCEL)
#define ELLIPSE_KEY_CLEAR  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CLEAR)
#define ELLIPSE_KEY_PRIOR  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_PRIOR)
#define ELLIPSE_KEY_RETURN2    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RETURN2)
#define ELLIPSE_KEY_SEPARATOR  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SEPARATOR)
#define ELLIPSE_KEY_OUT    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_OUT)
#define ELLIPSE_KEY_OPER   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_OPER)
#define ELLIPSE_KEY_CLEARAGAIN ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CLEARAGAIN)
#define ELLIPSE_KEY_CRSEL  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CRSEL)
#define ELLIPSE_KEY_EXSEL  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_EXSEL)
#define ELLIPSE_KEY_KP_00  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_00)
#define ELLIPSE_KEY_KP_000 ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_000)
#define ELLIPSE_KEY_THOUSANDSSEPARATOR ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_THOUSANDSSEPARATOR)
#define ELLIPSE_KEY_DECIMALSEPARATOR   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_DECIMALSEPARATOR)
#define ELLIPSE_KEY_CURRENCYUNIT   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CURRENCYUNIT)
#define ELLIPSE_KEY_CURRENCYSUBUNIT    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CURRENCYSUBUNIT)
#define ELLIPSE_KEY_KP_LEFTPAREN   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_LEFTPAREN)
#define ELLIPSE_KEY_KP_RIGHTPAREN  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_RIGHTPAREN)
#define ELLIPSE_KEY_KP_LEFTBRACE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_LEFTBRACE)
#define ELLIPSE_KEY_KP_RIGHTBRACE  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_RIGHTBRACE)
#define ELLIPSE_KEY_KP_TAB ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_TAB)
#define ELLIPSE_KEY_KP_BACKSPACE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_BACKSPACE)
#define ELLIPSE_KEY_KP_A   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_A)
#define ELLIPSE_KEY_KP_B   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_B)
#define ELLIPSE_KEY_KP_C   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_C)
#define ELLIPSE_KEY_KP_D   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_D)
#define ELLIPSE_KEY_KP_E   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_E)
#define ELLIPSE_KEY_KP_F   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_F)
#define ELLIPSE_KEY_KP_XOR ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_XOR)
#define ELLIPSE_KEY_KP_POWER   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_POWER)
#define ELLIPSE_KEY_KP_PERCENT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_PERCENT)
#define ELLIPSE_KEY_KP_LESS    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_LESS)
#define ELLIPSE_KEY_KP_GREATER ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_GREATER)
#define ELLIPSE_KEY_KP_AMPERSAND   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_AMPERSAND)
#define ELLIPSE_KEY_KP_DBLAMPERSAND    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_DBLAMPERSAND)
#define ELLIPSE_KEY_KP_VERTICALBAR ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_VERTICALBAR)
#define ELLIPSE_KEY_KP_DBLVERTICALBAR  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_DBLVERTICALBAR)
#define ELLIPSE_KEY_KP_COLON   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_COLON)
#define ELLIPSE_KEY_KP_HASH    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_HASH)
#define ELLIPSE_KEY_KP_SPACE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_SPACE)
#define ELLIPSE_KEY_KP_AT  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_AT)
#define ELLIPSE_KEY_KP_EXCLAM  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_EXCLAM)
#define ELLIPSE_KEY_KP_MEMSTORE    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMSTORE)
#define ELLIPSE_KEY_KP_MEMRECALL   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMRECALL)
#define ELLIPSE_KEY_KP_MEMCLEAR    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMCLEAR)
#define ELLIPSE_KEY_KP_MEMADD  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMADD)
#define ELLIPSE_KEY_KP_MEMSUBTRACT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMSUBTRACT)
#define ELLIPSE_KEY_KP_MEMMULTIPLY ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMMULTIPLY)
#define ELLIPSE_KEY_KP_MEMDIVIDE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_MEMDIVIDE)
#define ELLIPSE_KEY_KP_PLUSMINUS   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_PLUSMINUS)
#define ELLIPSE_KEY_KP_CLEAR   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_CLEAR)
#define ELLIPSE_KEY_KP_CLEARENTRY  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_CLEARENTRY)
#define ELLIPSE_KEY_KP_BINARY  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_BINARY)
#define ELLIPSE_KEY_KP_OCTAL   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_OCTAL)
#define ELLIPSE_KEY_KP_DECIMAL ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_DECIMAL)
#define ELLIPSE_KEY_KP_HEXADECIMAL ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KP_HEXADECIMAL)
#define ELLIPSE_KEY_LCTRL  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_LCTRL)
#define ELLIPSE_KEY_LSHIFT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_LSHIFT)
#define ELLIPSE_KEY_LALT   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_LALT)
#define ELLIPSE_KEY_LGUI   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_LGUI)
#define ELLIPSE_KEY_RCTRL  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RCTRL)
#define ELLIPSE_KEY_RSHIFT ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RSHIFT)
#define ELLIPSE_KEY_RALT   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RALT)
#define ELLIPSE_KEY_RGUI   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_RGUI)
#define ELLIPSE_KEY_MODE   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_MODE)
#define ELLIPSE_KEY_AUDIONEXT  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIONEXT)
#define ELLIPSE_KEY_AUDIOPREV  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOPREV)
#define ELLIPSE_KEY_AUDIOSTOP  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOSTOP)
#define ELLIPSE_KEY_AUDIOPLAY  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOPLAY)
#define ELLIPSE_KEY_AUDIOMUTE  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOMUTE)
#define ELLIPSE_KEY_MEDIASELECT    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_MEDIASELECT)
#define ELLIPSE_KEY_WWW    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_WWW)
#define ELLIPSE_KEY_MAIL   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_MAIL)
#define ELLIPSE_KEY_CALCULATOR ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CALCULATOR)
#define ELLIPSE_KEY_COMPUTER   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_COMPUTER)
#define ELLIPSE_KEY_AC_SEARCH  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_SEARCH)
#define ELLIPSE_KEY_AC_HOME    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_HOME)
#define ELLIPSE_KEY_AC_BACK    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_BACK)
#define ELLIPSE_KEY_AC_FORWARD ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_FORWARD)
#define ELLIPSE_KEY_AC_STOP    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_STOP)
#define ELLIPSE_KEY_AC_REFRESH ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_REFRESH)
#define ELLIPSE_KEY_AC_BOOKMARKS   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AC_BOOKMARKS)
#define ELLIPSE_KEY_BRIGHTNESSDOWN ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_BRIGHTNESSDOWN)
#define ELLIPSE_KEY_BRIGHTNESSUP   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_BRIGHTNESSUP)
#define ELLIPSE_KEY_DISPLAYSWITCH  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_DISPLAYSWITCH)
#define ELLIPSE_KEY_KBDILLUMTOGGLE ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KBDILLUMTOGGLE)
#define ELLIPSE_KEY_KBDILLUMDOWN   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KBDILLUMDOWN)
#define ELLIPSE_KEY_KBDILLUMUP ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_KBDILLUMUP)
#define ELLIPSE_KEY_EJECT  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_EJECT)
#define ELLIPSE_KEY_SLEEP  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SLEEP)
#define ELLIPSE_KEY_APP1   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_APP1)
#define ELLIPSE_KEY_APP2   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_APP2)
#define ELLIPSE_KEY_AUDIOREWIND    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOREWIND)
#define ELLIPSE_KEY_AUDIOFASTFORWARD   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_AUDIOFASTFORWARD)
#define ELLIPSE_KEY_SOFTLEFT   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SOFTLEFT)
#define ELLIPSE_KEY_SOFTRIGHT  ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_SOFTRIGHT)
#define ELLIPSE_KEY_CALL   ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_CALL)
#define ELLIPSE_KEY_ENDCALL    ELLIPSE_SCANCODE_TO_KEYCODE(ELLIPSE_SCANCODE_ENDCALL)

inline ScanCode keyCodeToScanCode(const KeyCode& k)
{
    switch(k)
     {
    case ELLIPSE_KEY_RETURN:
 return ELLIPSE_SCANCODE_RETURN;
    case ELLIPSE_KEY_ESCAPE:
 return ELLIPSE_SCANCODE_ESCAPE;
    case ELLIPSE_KEY_BACKSPACE:
 return ELLIPSE_SCANCODE_BACKSPACE;
    case ELLIPSE_KEY_TAB:
 return ELLIPSE_SCANCODE_TAB;
    case ELLIPSE_KEY_SPACE:
 return ELLIPSE_SCANCODE_SPACE;
case ELLIPSE_KEY_EXCLAIM:
 return ELLIPSE_SCANCODE_KP_EXCLAM;
// case ELLIPSE_KEY_DBLAPOSTROPHE:
case ELLIPSE_KEY_HASH:
    return ELLIPSE_SCANCODE_KP_HASH;
case ELLIPSE_KEY_PERCENT:
    return ELLIPSE_SCANCODE_KP_PERCENT;
// case ELLIPSE_KEY_DOLLAR:
case ELLIPSE_KEY_AMPERSAND:
    return ELLIPSE_SCANCODE_KP_AMPERSAND;
case ELLIPSE_KEY_APOSTROPHE:
    return ELLIPSE_SCANCODE_APOSTROPHE;
case ELLIPSE_KEY_LEFTPAREN:
    return ELLIPSE_SCANCODE_KP_LEFTPAREN;
case ELLIPSE_KEY_RIGHTPAREN:
    return ELLIPSE_SCANCODE_KP_RIGHTPAREN;
    // case ELLIPSE_KEY_ASTERISK:
    case ELLIPSE_KEY_PLUS:
   return ELLIPSE_SCANCODE_KP_PLUS;
    case ELLIPSE_KEY_COMMA:
   return ELLIPSE_SCANCODE_COMMA;
    case ELLIPSE_KEY_MINUS:
   return ELLIPSE_SCANCODE_KP_MINUS;
    case ELLIPSE_KEY_PERIOD:
   return ELLIPSE_SCANCODE_KP_PERIOD;
    case ELLIPSE_KEY_SLASH:
   return ELLIPSE_SCANCODE_SLASH;
    case ELLIPSE_KEY_0:
   return ELLIPSE_SCANCODE_0;
    case ELLIPSE_KEY_1:
      return ELLIPSE_SCANCODE_1;
    case ELLIPSE_KEY_2:
      return ELLIPSE_SCANCODE_2;
    case ELLIPSE_KEY_3:
      return ELLIPSE_SCANCODE_3;
    case ELLIPSE_KEY_4:
      return ELLIPSE_SCANCODE_4;
    case ELLIPSE_KEY_5:
      return ELLIPSE_SCANCODE_5;
    case ELLIPSE_KEY_6:
      return ELLIPSE_SCANCODE_6;
    case ELLIPSE_KEY_7:
      return ELLIPSE_SCANCODE_7;
    case ELLIPSE_KEY_8:
      return ELLIPSE_SCANCODE_8;
    case ELLIPSE_KEY_9:
      return ELLIPSE_SCANCODE_9;
    case ELLIPSE_KEY_COLON:
     return ELLIPSE_SCANCODE_KP_COLON;
    case ELLIPSE_KEY_SEMICOLON:
     return ELLIPSE_SCANCODE_SEMICOLON;
    case ELLIPSE_KEY_LESS:
     return ELLIPSE_SCANCODE_KP_LESS;
    case ELLIPSE_KEY_EQUALS:
     return ELLIPSE_SCANCODE_EQUALS;
    case ELLIPSE_KEY_GREATER:
     return ELLIPSE_SCANCODE_KP_GREATER;
    // case ELLIPSE_KEY_QUESTION:
    case ELLIPSE_KEY_AT:
     return ELLIPSE_SCANCODE_KP_AT;
      case ELLIPSE_KEY_LEFTBRACKET:
    return ELLIPSE_SCANCODE_LEFTBRACKET;
      case ELLIPSE_KEY_BACKSLASH:
    return ELLIPSE_SCANCODE_BACKSLASH;
    case ELLIPSE_KEY_RIGHTBRACKET:
    return ELLIPSE_SCANCODE_RIGHTBRACKET;
// case ELLIPSE_KEY_CARET  '^'
// case ELLIPSE_KEY_UNDERSCORE '_'
      case ELLIPSE_KEY_GRAVE:
    return ELLIPSE_SCANCODE_GRAVE;
      case ELLIPSE_KEY_a:
    return ELLIPSE_SCANCODE_A;
     case ELLIPSE_KEY_b:
    return ELLIPSE_SCANCODE_B;
     case ELLIPSE_KEY_c:
    return ELLIPSE_SCANCODE_C;
     case ELLIPSE_KEY_d:
    return ELLIPSE_SCANCODE_D;
     case ELLIPSE_KEY_e:
    return ELLIPSE_SCANCODE_E;
      case ELLIPSE_KEY_f:
    return ELLIPSE_SCANCODE_F;
      case ELLIPSE_KEY_g:
    return ELLIPSE_SCANCODE_G;
     case ELLIPSE_KEY_h:
    return ELLIPSE_SCANCODE_H;
    case ELLIPSE_KEY_i:
    return ELLIPSE_SCANCODE_I;
    case ELLIPSE_KEY_j:
    return ELLIPSE_SCANCODE_J;
    case ELLIPSE_KEY_k:
    return ELLIPSE_SCANCODE_K;
    case ELLIPSE_KEY_l:
    return ELLIPSE_SCANCODE_L;
case ELLIPSE_KEY_m:
    return ELLIPSE_SCANCODE_M;
case ELLIPSE_KEY_n:
    return ELLIPSE_SCANCODE_N;
case ELLIPSE_KEY_o:
    return ELLIPSE_SCANCODE_O;
case ELLIPSE_KEY_p:
    return ELLIPSE_SCANCODE_P;
case ELLIPSE_KEY_q:
    return ELLIPSE_SCANCODE_Q;
case ELLIPSE_KEY_r:
    return ELLIPSE_SCANCODE_R;
case ELLIPSE_KEY_s:
    return ELLIPSE_SCANCODE_S;
case ELLIPSE_KEY_t:
    return ELLIPSE_SCANCODE_T;
case ELLIPSE_KEY_u:
    return ELLIPSE_SCANCODE_U;
case ELLIPSE_KEY_v:
    return ELLIPSE_SCANCODE_V;
case ELLIPSE_KEY_w:
    return ELLIPSE_SCANCODE_W;
case ELLIPSE_KEY_x:
    return ELLIPSE_SCANCODE_X;
case ELLIPSE_KEY_y:
    return ELLIPSE_SCANCODE_Y;
case ELLIPSE_KEY_z:
    return ELLIPSE_SCANCODE_Z;
   case ELLIPSE_KEY_CAPSLOCK:
    return ELLIPSE_SCANCODE_CAPSLOCK;
    case ELLIPSE_KEY_F1:
    return ELLIPSE_SCANCODE_F1;
    case ELLIPSE_KEY_F2:
    return ELLIPSE_SCANCODE_F2;
    case ELLIPSE_KEY_F3:
    return ELLIPSE_SCANCODE_F3;
    case ELLIPSE_KEY_F4:
    return ELLIPSE_SCANCODE_F4;
    case ELLIPSE_KEY_F5:
    return ELLIPSE_SCANCODE_F5;
    case ELLIPSE_KEY_F6:
    return ELLIPSE_SCANCODE_F6;
    case ELLIPSE_KEY_F7:
    return ELLIPSE_SCANCODE_F7;
    case ELLIPSE_KEY_F8:
    return ELLIPSE_SCANCODE_F8;
    case ELLIPSE_KEY_F9:
    return ELLIPSE_SCANCODE_F9;
    case ELLIPSE_KEY_F10:
    return ELLIPSE_SCANCODE_F10;
    case ELLIPSE_KEY_F11:
    return ELLIPSE_SCANCODE_F11;
    case ELLIPSE_KEY_F12:
    return ELLIPSE_SCANCODE_F12;
    case ELLIPSE_KEY_PRINTSCREEN:
    return ELLIPSE_SCANCODE_PRINTSCREEN;
    case ELLIPSE_KEY_SCROLLLOCK:
    return ELLIPSE_SCANCODE_SCROLLLOCK;
case ELLIPSE_KEY_PAUSE:
    return ELLIPSE_SCANCODE_PAUSE;
    case ELLIPSE_KEY_INSERT:
      return ELLIPSE_SCANCODE_INSERT;
    case ELLIPSE_KEY_HOME:
     return ELLIPSE_SCANCODE_HOME;
    case ELLIPSE_KEY_PAGEUP:
     return ELLIPSE_SCANCODE_PAGEUP;
    case ELLIPSE_KEY_DELETE:
    return ELLIPSE_SCANCODE_DELETE;
    case ELLIPSE_KEY_END:
    return ELLIPSE_SCANCODE_END;
    case ELLIPSE_KEY_PAGEDOWN:
     return ELLIPSE_SCANCODE_PAGEDOWN;
    case ELLIPSE_KEY_RIGHT:
     return ELLIPSE_SCANCODE_RIGHT;
case ELLIPSE_KEY_LEFT:  
     return ELLIPSE_SCANCODE_LEFT;
case ELLIPSE_KEY_DOWN:  
     return ELLIPSE_SCANCODE_DOWN;
    case ELLIPSE_KEY_UP:
     return ELLIPSE_SCANCODE_UP;
    case ELLIPSE_KEY_NUMLOCKCLEAR:
     return ELLIPSE_SCANCODE_NUMLOCKCLEAR;
    case ELLIPSE_KEY_KP_DIVIDE:
     return ELLIPSE_SCANCODE_KP_DIVIDE;
    case ELLIPSE_KEY_KP_MULTIPLY:
     return ELLIPSE_SCANCODE_KP_MULTIPLY;
    case ELLIPSE_KEY_KP_MINUS:
     return ELLIPSE_SCANCODE_KP_MINUS;
    case ELLIPSE_KEY_KP_PLUS:
     return ELLIPSE_SCANCODE_KP_PLUS;
    case ELLIPSE_KEY_KP_ENTER:
     return ELLIPSE_SCANCODE_KP_ENTER;
    case ELLIPSE_KEY_KP_1:
     return ELLIPSE_SCANCODE_KP_1;
    case ELLIPSE_KEY_KP_2:
     return ELLIPSE_SCANCODE_KP_2;
    case ELLIPSE_KEY_KP_3:
     return ELLIPSE_SCANCODE_KP_3;
    case ELLIPSE_KEY_KP_4:
     return ELLIPSE_SCANCODE_KP_4;
    case ELLIPSE_KEY_KP_5:
     return ELLIPSE_SCANCODE_KP_5;
    case ELLIPSE_KEY_KP_6:
     return ELLIPSE_SCANCODE_KP_6;
    case ELLIPSE_KEY_KP_7:
     return ELLIPSE_SCANCODE_KP_7;
    case ELLIPSE_KEY_KP_8:
     return ELLIPSE_SCANCODE_KP_8;
    case ELLIPSE_KEY_KP_9:
     return ELLIPSE_SCANCODE_KP_9;
    case ELLIPSE_KEY_KP_0:
     return ELLIPSE_SCANCODE_KP_0;
    case ELLIPSE_KEY_KP_PERIOD:  
     return ELLIPSE_SCANCODE_KP_PERIOD;
    case ELLIPSE_KEY_APPLICATION:
     return ELLIPSE_SCANCODE_APPLICATION;
    case ELLIPSE_KEY_POWER:
     return ELLIPSE_SCANCODE_POWER;
    case ELLIPSE_KEY_KP_EQUALS: 
     return ELLIPSE_SCANCODE_KP_EQUALS;
    case ELLIPSE_KEY_F13:
     return ELLIPSE_SCANCODE_F13;
    case ELLIPSE_KEY_F14:
     return ELLIPSE_SCANCODE_F14;
    case ELLIPSE_KEY_F15:
     return ELLIPSE_SCANCODE_F15;
    case ELLIPSE_KEY_F16:
     return ELLIPSE_SCANCODE_F16;
    case ELLIPSE_KEY_F17:
     return ELLIPSE_SCANCODE_F17;
    case ELLIPSE_KEY_F18:
     return ELLIPSE_SCANCODE_F18;
    case ELLIPSE_KEY_F19:
     return ELLIPSE_SCANCODE_F19;
    case ELLIPSE_KEY_F20:
     return ELLIPSE_SCANCODE_F20;
    case ELLIPSE_KEY_F21:
     return ELLIPSE_SCANCODE_F21;
    case ELLIPSE_KEY_F22:
     return ELLIPSE_SCANCODE_F22;
    case ELLIPSE_KEY_F23:
     return ELLIPSE_SCANCODE_F23;
    case ELLIPSE_KEY_F24:
     return ELLIPSE_SCANCODE_F24;
    case ELLIPSE_KEY_EXECUTE:   
     return ELLIPSE_SCANCODE_EXECUTE;
    case ELLIPSE_KEY_HELP:
     return ELLIPSE_SCANCODE_HELP;
    case ELLIPSE_KEY_MENU:
     return ELLIPSE_SCANCODE_MENU;
    case ELLIPSE_KEY_SELECT:
     return ELLIPSE_SCANCODE_SELECT;
    case ELLIPSE_KEY_STOP:
     return ELLIPSE_SCANCODE_STOP;
    case ELLIPSE_KEY_AGAIN:
     return ELLIPSE_SCANCODE_AGAIN;
    case ELLIPSE_KEY_UNDO:
     return ELLIPSE_SCANCODE_UNDO;
    case ELLIPSE_KEY_CUT:
     return ELLIPSE_SCANCODE_CUT;
    case ELLIPSE_KEY_COPY:
     return ELLIPSE_SCANCODE_COPY;
    case ELLIPSE_KEY_PASTE:
     return ELLIPSE_SCANCODE_PASTE;
    case ELLIPSE_KEY_FIND:
     return ELLIPSE_SCANCODE_FIND;
    case ELLIPSE_KEY_MUTE: 
     return ELLIPSE_SCANCODE_MUTE;
    case ELLIPSE_KEY_VOLUMEUP:  
     return ELLIPSE_SCANCODE_VOLUMEUP;
    case ELLIPSE_KEY_VOLUMEDOWN:
     return ELLIPSE_SCANCODE_VOLUMEDOWN;
    case ELLIPSE_KEY_KP_COMMA:
     return ELLIPSE_SCANCODE_KP_COMMA;
    case ELLIPSE_KEY_KP_EQUALSAS400:
     return ELLIPSE_SCANCODE_KP_EQUALSAS400;
    case ELLIPSE_KEY_ALTERASE:
     return ELLIPSE_SCANCODE_ALTERASE;
    case ELLIPSE_KEY_SYSREQ:
     return ELLIPSE_SCANCODE_SYSREQ;
    case ELLIPSE_KEY_CANCEL:
     return ELLIPSE_SCANCODE_CANCEL;
    case ELLIPSE_KEY_CLEAR:
     return ELLIPSE_SCANCODE_CLEAR;
    case ELLIPSE_KEY_PRIOR:
     return ELLIPSE_SCANCODE_PRIOR;
    case ELLIPSE_KEY_RETURN2:
     return ELLIPSE_SCANCODE_RETURN2;
    case ELLIPSE_KEY_SEPARATOR:
     return ELLIPSE_SCANCODE_SEPARATOR;
    case ELLIPSE_KEY_OUT:
     return ELLIPSE_SCANCODE_OUT;
    case ELLIPSE_KEY_OPER:
     return ELLIPSE_SCANCODE_OPER;
    case ELLIPSE_KEY_CLEARAGAIN:
     return ELLIPSE_SCANCODE_CLEARAGAIN;
    case ELLIPSE_KEY_CRSEL:
     return ELLIPSE_SCANCODE_CRSEL;
    case ELLIPSE_KEY_EXSEL: 
     return ELLIPSE_SCANCODE_EXSEL;
    case ELLIPSE_KEY_KP_00: 
     return ELLIPSE_SCANCODE_KP_00;
    case ELLIPSE_KEY_KP_000:
     return ELLIPSE_SCANCODE_KP_000;
case ELLIPSE_KEY_THOUSANDSSEPARATOR:
    return ELLIPSE_SCANCODE_THOUSANDSSEPARATOR;
case ELLIPSE_KEY_DECIMALSEPARATOR:  
    return ELLIPSE_SCANCODE_DECIMALSEPARATOR;
case ELLIPSE_KEY_CURRENCYUNIT:   
    return ELLIPSE_SCANCODE_CURRENCYUNIT;
case ELLIPSE_KEY_CURRENCYSUBUNIT:
    return ELLIPSE_SCANCODE_CURRENCYSUBUNIT;
case ELLIPSE_KEY_KP_LEFTPAREN: 
    return ELLIPSE_SCANCODE_KP_LEFTPAREN;
case ELLIPSE_KEY_KP_RIGHTPAREN:
    return ELLIPSE_SCANCODE_KP_RIGHTPAREN;
case ELLIPSE_KEY_KP_LEFTBRACE: 
    return ELLIPSE_SCANCODE_KP_LEFTBRACE;
case ELLIPSE_KEY_KP_RIGHTBRACE:
    return ELLIPSE_SCANCODE_KP_RIGHTBRACE;
case ELLIPSE_KEY_KP_TAB:
    return ELLIPSE_SCANCODE_KP_TAB;
case ELLIPSE_KEY_KP_BACKSPACE: 
    return ELLIPSE_SCANCODE_KP_BACKSPACE;
case ELLIPSE_KEY_KP_A:
    return ELLIPSE_SCANCODE_KP_A;
case ELLIPSE_KEY_KP_B:
    return ELLIPSE_SCANCODE_KP_B;
case ELLIPSE_KEY_KP_C:
    return ELLIPSE_SCANCODE_KP_C;
case ELLIPSE_KEY_KP_D:
    return ELLIPSE_SCANCODE_KP_D;
case ELLIPSE_KEY_KP_E:
    return ELLIPSE_SCANCODE_KP_E;
case ELLIPSE_KEY_KP_F:
    return ELLIPSE_SCANCODE_KP_F;
case ELLIPSE_KEY_KP_XOR:
    return ELLIPSE_SCANCODE_KP_XOR;
case ELLIPSE_KEY_KP_POWER:  
    return ELLIPSE_SCANCODE_KP_POWER;
case ELLIPSE_KEY_KP_PERCENT:
    return ELLIPSE_SCANCODE_KP_PERCENT;
case ELLIPSE_KEY_KP_LESS:   
    return ELLIPSE_SCANCODE_KP_LESS;
case ELLIPSE_KEY_KP_GREATER:
    return ELLIPSE_SCANCODE_KP_GREATER;
case ELLIPSE_KEY_KP_AMPERSAND:
    return ELLIPSE_SCANCODE_KP_AMPERSAND;
case ELLIPSE_KEY_KP_DBLAMPERSAND:
    return ELLIPSE_SCANCODE_KP_DBLAMPERSAND;
case ELLIPSE_KEY_KP_VERTICALBAR:
    return ELLIPSE_SCANCODE_KP_VERTICALBAR;
case ELLIPSE_KEY_KP_DBLVERTICALBAR:
    return ELLIPSE_SCANCODE_KP_DBLVERTICALBAR;
case ELLIPSE_KEY_KP_COLON:
    return ELLIPSE_SCANCODE_KP_COLON;
case ELLIPSE_KEY_KP_HASH: 
    return ELLIPSE_SCANCODE_KP_HASH;
case ELLIPSE_KEY_KP_SPACE:
    return ELLIPSE_SCANCODE_KP_SPACE;
case ELLIPSE_KEY_KP_AT: 
    return ELLIPSE_SCANCODE_KP_AT;
case ELLIPSE_KEY_KP_EXCLAM: 
    return ELLIPSE_SCANCODE_KP_EXCLAM;
case ELLIPSE_KEY_KP_MEMSTORE:
    return ELLIPSE_SCANCODE_KP_MEMSTORE;
case ELLIPSE_KEY_KP_MEMRECALL:
    return ELLIPSE_SCANCODE_KP_MEMRECALL;
case ELLIPSE_KEY_KP_MEMCLEAR: 
    return ELLIPSE_SCANCODE_KP_MEMCLEAR;
case ELLIPSE_KEY_KP_MEMADD: 
    return ELLIPSE_SCANCODE_KP_MEMADD;
case ELLIPSE_KEY_KP_MEMSUBTRACT:
    return ELLIPSE_SCANCODE_KP_MEMSUBTRACT;
case ELLIPSE_KEY_KP_MEMMULTIPLY:
    return ELLIPSE_SCANCODE_KP_MEMMULTIPLY;
case ELLIPSE_KEY_KP_MEMDIVIDE:  
    return ELLIPSE_SCANCODE_KP_MEMDIVIDE;
case ELLIPSE_KEY_KP_PLUSMINUS:  
    return ELLIPSE_SCANCODE_KP_PLUSMINUS;
case ELLIPSE_KEY_KP_CLEAR:
    return ELLIPSE_SCANCODE_KP_CLEAR;
case ELLIPSE_KEY_KP_CLEARENTRY:
    return ELLIPSE_SCANCODE_KP_CLEARENTRY;
case ELLIPSE_KEY_KP_BINARY:  
    return ELLIPSE_SCANCODE_KP_BINARY;
case ELLIPSE_KEY_KP_OCTAL:   
    return ELLIPSE_SCANCODE_KP_OCTAL;
case ELLIPSE_KEY_KP_DECIMAL: 
    return ELLIPSE_SCANCODE_KP_DECIMAL;
case ELLIPSE_KEY_KP_HEXADECIMAL:
    return ELLIPSE_SCANCODE_KP_HEXADECIMAL;
case ELLIPSE_KEY_LCTRL:  
    return ELLIPSE_SCANCODE_LCTRL;
case ELLIPSE_KEY_LSHIFT: 
    return ELLIPSE_SCANCODE_LSHIFT;
case ELLIPSE_KEY_LALT:   
    return ELLIPSE_SCANCODE_LALT ;
case ELLIPSE_KEY_LGUI:   
    return ELLIPSE_SCANCODE_LGUI;
case ELLIPSE_KEY_RCTRL:  
    return ELLIPSE_SCANCODE_RCTRL;
case ELLIPSE_KEY_RSHIFT: 
    return ELLIPSE_SCANCODE_RSHIFT;
case ELLIPSE_KEY_RALT:   
    return ELLIPSE_SCANCODE_RALT;
case ELLIPSE_KEY_RGUI:   
    return ELLIPSE_SCANCODE_RGUI;
case ELLIPSE_KEY_MODE:   
    return ELLIPSE_SCANCODE_MODE;
case ELLIPSE_KEY_AUDIONEXT:
    return ELLIPSE_SCANCODE_AUDIONEXT;
case ELLIPSE_KEY_AUDIOPREV:
    return ELLIPSE_SCANCODE_AUDIOPREV;
case ELLIPSE_KEY_AUDIOSTOP:
    return ELLIPSE_SCANCODE_AUDIOSTOP;
case ELLIPSE_KEY_AUDIOPLAY:
    return ELLIPSE_SCANCODE_AUDIOPLAY;
case ELLIPSE_KEY_AUDIOMUTE:
    return ELLIPSE_SCANCODE_AUDIOMUTE;
case ELLIPSE_KEY_MEDIASELECT:
    return ELLIPSE_SCANCODE_MEDIASELECT;
case ELLIPSE_KEY_WWW:    
    return ELLIPSE_SCANCODE_WWW;
case ELLIPSE_KEY_MAIL:  
    return ELLIPSE_SCANCODE_MAIL;
case ELLIPSE_KEY_CALCULATOR: 
    return ELLIPSE_SCANCODE_CALCULATOR;
case ELLIPSE_KEY_COMPUTER:   
    return ELLIPSE_SCANCODE_COMPUTER;
case ELLIPSE_KEY_AC_SEARCH:  
    return ELLIPSE_SCANCODE_AC_SEARCH;
case ELLIPSE_KEY_AC_HOME:    
    return ELLIPSE_SCANCODE_AC_HOME;
case ELLIPSE_KEY_AC_BACK:    
    return ELLIPSE_SCANCODE_AC_BACK;
case ELLIPSE_KEY_AC_FORWARD: 
    return ELLIPSE_SCANCODE_AC_FORWARD;
case ELLIPSE_KEY_AC_STOP:    
    return ELLIPSE_SCANCODE_AC_STOP;
case ELLIPSE_KEY_AC_REFRESH: 
    return ELLIPSE_SCANCODE_AC_REFRESH;
case ELLIPSE_KEY_AC_BOOKMARKS:  
    return ELLIPSE_SCANCODE_AC_BOOKMARKS;
case ELLIPSE_KEY_BRIGHTNESSDOWN:
    return ELLIPSE_SCANCODE_BRIGHTNESSDOWN;
case ELLIPSE_KEY_BRIGHTNESSUP:  
    return ELLIPSE_SCANCODE_BRIGHTNESSUP;
case ELLIPSE_KEY_DISPLAYSWITCH: 
    return ELLIPSE_SCANCODE_DISPLAYSWITCH;
case ELLIPSE_KEY_KBDILLUMTOGGLE:
    return ELLIPSE_SCANCODE_KBDILLUMTOGGLE;
case ELLIPSE_KEY_KBDILLUMDOWN:  
    return ELLIPSE_SCANCODE_KBDILLUMDOWN;
case ELLIPSE_KEY_KBDILLUMUP:
    return ELLIPSE_SCANCODE_KBDILLUMUP;
case ELLIPSE_KEY_EJECT:
    return ELLIPSE_SCANCODE_EJECT;
case ELLIPSE_KEY_SLEEP:
    return ELLIPSE_SCANCODE_SLEEP;
case ELLIPSE_KEY_APP1: 
    return ELLIPSE_SCANCODE_APP1;
case ELLIPSE_KEY_APP2: 
    return ELLIPSE_SCANCODE_APP2;
case ELLIPSE_KEY_AUDIOREWIND:
    return ELLIPSE_SCANCODE_AUDIOREWIND;
case ELLIPSE_KEY_AUDIOFASTFORWARD:
    return ELLIPSE_SCANCODE_AUDIOFASTFORWARD;
case ELLIPSE_KEY_SOFTLEFT:   
    return ELLIPSE_SCANCODE_SOFTLEFT;
case ELLIPSE_KEY_SOFTRIGHT:  
    return ELLIPSE_SCANCODE_SOFTRIGHT;
case ELLIPSE_KEY_CALL:
    return ELLIPSE_SCANCODE_CALL;
case ELLIPSE_KEY_ENDCALL:   
    return ELLIPSE_SCANCODE_ENDCALL;
  default:
   return ELLIPSE_SCANCODE_UNKNOWN;
     }

   return ELLIPSE_SCANCODE_UNKNOWN;
}
